name: my_tmdb
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.2
  dfunc: ^0.8.0+1
  dio: ^4.0.6
  fast_immutable_collections: ^7.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  palette_generator: ^0.3.3+2
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  stream_transform: ^2.0.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  golden_toolkit: ^0.13.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.4.1
  mews_pedantic: ^0.8.0
  mockito: ^5.3.2
  retrofit_generator: ^4.1.1

flutter:
  uses-material-design: true
